<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-R3M2R8E" failures="2" tests="2" name="Test" time="16.548" errors="0" timestamp="10 Jan 2021 05:42:06 GMT">
  <testcase classname="Academy.Validatetitle" name="verifytitle" time="16.484">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Academy.Validatetitle.verifytitle(Validatetitle.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifytitle -->
  <testcase classname="Academy.Validatetitle" name="verifytitle" time="16.527">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.Base.TakeScreenshot(Base.java:53)
at Academy.listeners.onTestFailure(listeners.java:34)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifytitle -->
</testsuite> <!-- Test -->
